### ISSUE TITLE
Let us know when MELPA is ready

### ISSUE THREAD

**Issue by Ypot** [kadircancetin/typo-suggest#2]
Many times I hope to have on my PC the "inteligent" keyboard I have on the mobile, where I can write in many languages correctly because I just have to choose the word. It seems your solution is coming to fill this gap.
Thanks

**Comment by kadircancetin** [comment]
Thank you. Actually it is available on melpa. I just don't have to time fix README. 

I am writing an ispell backend for local completion, I had a plan to promote after ispell backend done and fix the documentation. I don't expect that someone finds this package :)

So I will fix the documentation. You can currently download via `package-install` or any type of way you want. 

I think the company backend is not as good as your needs, please let me know if you try. Maybe I can help.

**Comment by Ypot** [comment]
It looks great! **It works out of the box.**
I think I will love it.

Offtopic: I have tried to use your assitant with several words in a row, without invoking it. I thought it should be done using company-mode but it doesn't seem to work that way. It would be nice to be able to activate it permanenlty just using a command.

**Comment by kadircancetin** [comment]
Thanks for your advice. I think I could write a minor mode for that. Activating and deactivating will be very easy on company-mode. And I will try to write more smart helm completion, if there is a  word it will replace, if there isn't it will insert. We will not need two keys for this job.

I will close this issue. If I implement it, I will let you know. Thanks again.

**Comment by kadircancetin** [comment]
I update the package. You can check it if you want.

**Comment by Ypot** [comment]
> 
> 
> I update the package. You can check it if you want.

When I choose a word the cursor is placed in the beginning of that word. It should be placed at the end of the inserted word to keep writing.

Still I can not activate permanently the suggestions for several words in a row, at least using the commands typo-`suggest-company-mode` nor `typo-suggest-company`. I haven't tried yet modifying the .init file.

**Note: it seems it will look great soon!**
